name: 'AppCenter CLI Action'
description: 'Github Action for installing the AppCenter CLI and running commands with it.'
author: 'charliealbright'
branding:
  icon: 'smartphone'
  color: 'red'
inputs:
  token:
    required: true
    description: 'AppCenter Token to authenticate with CLI'
  command:
    required: true
    description: 'Command to run with the CLI'
  cliVersionOverride:
    required: false
    description: 'Configure this action to use a specific version of the CLI'
runs:
  using: 'node18'
  main: 'dist/index.js'
