name: 'build-test'
on: # rebuild any PRs and main branch changes
  pull_request_target:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          npm install
      - run: |
          npm run all
  test: # Verify action functionality
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: (PASS) AppCenter Help
        uses: ./
        with:
          token: ${{ secrets.APPCENTER_TOKEN }}
          command: appcenter help

      - name: (PASS) Version Override works
        uses: ./
        with:
          token: ${{ secrets.APPCENTER_TOKEN }}
          command: appcenter help
          cliVersionOverride: 2.13.0

      - name: (PASS) List apps
        uses: ./
        with:
          token: ${{ secrets.APPCENTER_TOKEN }}
          command: appcenter apps list
